/// Common musical instrument families from the bundled General MIDI bank.
/// Sound-effect presets and alternate sound banks are intentionally not offered.
const instrumentCategories = <String, Map<int, String>>{
  'Piano & Keyboards': {
    0: 'Grand piano',
    1: 'Bright grand piano',
    2: 'Electric grand piano',
    3: 'Honky-tonk piano',
    4: 'Electric piano',
    5: 'FM electric piano',
    6: 'Harpsichord',
    7: 'Clavinet',
  },
  'Organs & Accordions': {
    16: 'Drawbar organ',
    17: 'Percussive organ',
    18: 'Rock organ',
    19: 'Church organ',
    20: 'Reed organ',
    21: 'Accordion',
    22: 'Harmonica',
    23: 'Bandoneon',
  },
  'Guitars': {
    24: 'Nylon guitar',
    25: 'Steel-string guitar',
    26: 'Jazz guitar',
    27: 'Clean electric guitar',
    28: 'Muted guitar',
    29: 'Overdrive guitar',
    30: 'Distortion guitar',
    31: 'Guitar harmonics',
  },
  'Bass': {
    32: 'Acoustic bass',
    33: 'Finger bass',
    34: 'Pick bass',
    35: 'Fretless bass',
    36: 'Slap bass 1',
    37: 'Slap bass 2',
    38: 'Synth bass 1',
    39: 'Synth bass 2',
  },
  'Strings': {
    40: 'Violin',
    41: 'Viola',
    42: 'Cello',
    43: 'Double bass',
    44: 'Tremolo strings',
    45: 'Pizzicato strings',
    46: 'Orchestral harp',
    48: 'String ensemble',
    49: 'Slow strings',
    50: 'Synth strings 1',
    51: 'Synth strings 2',
  },
  'Choir & Voices': {
    52: 'Choir voices',
    53: 'Voice oohs',
    54: 'Synth voice',
  },
  'Brass': {
    56: 'Trumpet',
    57: 'Trombone',
    58: 'Tuba',
    59: 'Muted trumpet',
    60: 'French horns',
    61: 'Brass section',
    62: 'Synth brass 1',
    63: 'Synth brass 2',
  },
  'Woodwinds': {
    64: 'Soprano sax',
    65: 'Alto sax',
    66: 'Tenor sax',
    67: 'Baritone sax',
    68: 'Oboe',
    69: 'English horn',
    70: 'Bassoon',
    71: 'Clarinet',
    72: 'Piccolo',
    73: 'Flute',
    74: 'Recorder',
    75: 'Pan flute',
    76: 'Bottle blow',
    77: 'Shakuhachi',
    78: 'Whistle',
    79: 'Ocarina',
  },
  'Percussion': {
    8: 'Celeste',
    9: 'Glockenspiel',
    10: 'Music box',
    11: 'Vibraphone',
    12: 'Marimba',
    13: 'Xylophone',
    14: 'Tubular bells',
    15: 'Dulcimer',
    47: 'Timpani',
    112: 'Tinker bell',
    113: 'Agogo',
    114: 'Steelpan',
    115: 'Wood block',
    116: 'Taiko drum',
    117: 'Melodic tom',
    118: 'Synth drum',
    119: 'Reverse cymbal',
  },
  'Folk & Traditional': {
    104: 'Sitar',
    105: 'Banjo',
    106: 'Shamisen',
    107: 'Koto',
    108: 'Kalimba',
    109: 'Bagpipes',
    110: 'Fiddle',
    111: 'Shenai',
  },
  'Synthesizers': {
    80: 'Square lead',
    81: 'Saw lead',
    82: 'Synth calliope',
    83: 'Chiffer lead',
    84: 'Charang',
    85: 'Solo vox',
    86: '5th saw wave',
    87: 'Bass & lead',
    88: 'Fantasia',
    89: 'Warm pad',
    90: 'Polysynth',
    91: 'Space voice',
    92: 'Bowed glass',
    93: 'Metal pad',
    94: 'Halo pad',
    95: 'Sweep pad',
  },
};

final instrumentNames = <int, String>{
  for (final group in instrumentCategories.values) ...group,
};
