#!/usr/bin/env python3
"""Generate offline topical lists from the transcribed photos and local catalog."""
import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / 'tool/data/topical_index'


def build():
    catalog = json.loads((ROOT / 'assets/hymns.json').read_text())['hymns']
    valid = {v: {h['number'] for h in catalog if h['version'] == v}
             for v in ('new', 'old')}
    readings = {r['number'] for r in json.loads(
        (ROOT / 'assets/additional_readings.json').read_text())['readings']
        if r['edition'] == 'new'}
    cross = {}
    for work in json.loads((ROOT / 'assets/hymn_metadata.json').read_text())['hymns']:
        for number in work['numbers']['new']:
            cross[number] = [n for n in work['numbers']['old'] if n in valid['old']]
    # Exact normalized title matches supplement metadata cross-references.
    def normalized(title):
        return re.sub(r"[^a-z0-9]", "", title.lower())
    for hymn in catalog:
        if hymn['version'] == 'new':
            matches = [h['number'] for h in catalog if h['version'] == 'old'
                       and normalized(h['title']) == normalized(hymn['title'])]
            cross[hymn['number']] = list(dict.fromkeys(
                cross.get(hymn['number'], []) + matches))
    editorial_old = {
        'Health and Wholeness': [530],
        'Law and Grace': [163, 592],
        'New Year': [480],
        'Obedience': [288, 429, 279],
        'Spiritual Gifts': [207, 658],
    }
    rows = []
    for line in (DATA / 'new_hymnal.tsv').read_text().splitlines():
        if not line or line.startswith('#'):
            continue
        title, hymns, refs, photos = line.split('|')
        new = list(dict.fromkeys(map(int, hymns.split())))
        refs = list(dict.fromkeys(map(int, refs.split())))
        if title == 'Pilgrimage':
            new.append(622)  # Alternate setting of Come, Come, Ye Saints (629).
        assert set(new) <= valid['new'], title
        assert set(refs) <= readings, title
        old = list(dict.fromkeys(n for number in new for n in cross.get(number, [])))
        # This printed heading contains readings only. Editorial Old Hymnal
        # suggestions use existing cross-references for a consecrated life.
        if title == 'Christian Life':
            old = list(dict.fromkeys(n for number in [306, 309, 330, 590]
                                    for n in cross.get(number, [])))
        old = list(dict.fromkeys(old + editorial_old.get(title, [])))
        assert set(old) <= valid['old'], title
        rows.append(dict(title=title, newNumbers=new, oldNumbers=old,
                         newReadingNumbers=refs))
    lines = ['// Generated by tool/build_topical_index.py. Do not edit.',
             "part of 'hymn_occasion.dart';", '',
             'const printedTopicalIndex = <HymnOccasion>[']
    for row in rows:
        slug = re.sub('[^a-z0-9]+', '-', row['title'].lower()).strip('-')
        lines += ['  HymnOccasion(', f'    id: {json.dumps(slug)},',
                  f'    title: {json.dumps(row["title"])},',
                  '    description: "Hymns and readings for this topic.",']
        for key in ['newNumbers', 'oldNumbers', 'newReadingNumbers']:
            lines.append(f'    {key}: {row[key]},')
        lines.append('  ),')
    lines.append('];')
    aliases = json.loads((DATA / 'cross_references.json').read_text())
    titles = {r['title'] for r in rows}
    lines += ['', 'const topicalCrossReferences = <String, List<String>>{']
    for alias, targets in aliases.items():
        assert set(targets) <= titles, alias
        lines.append(f'  {json.dumps(alias, ensure_ascii=False)}: {json.dumps(targets, ensure_ascii=False)},')
    lines.append('};')
    (ROOT / 'lib/models/topical_index.g.dart').write_text('\n'.join(lines) + '\n')
    subprocess.run(['dart', 'format', str(ROOT / 'lib/models/topical_index.g.dart')],
                   check=True, capture_output=True)
    print(f'Generated {len(rows)} topics; '
          f'{sum(len(r["newNumbers"]) for r in rows)} hymn memberships; '
          f'{sum(len(r["newReadingNumbers"]) for r in rows)} reading memberships.')
    print('Old topics without hymns:', [r['title'] for r in rows if not r['oldNumbers']])


if __name__ == '__main__':
    build()
